name: Deploy to EKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1  # Set your AWS region


    - name: Configure to EKS
      run: |
        aws eks update-kubeconfig --region ca-central-1 --name my-cluster
        kubectl get ns
        kubectl apply -f mysql-secrets.yml -f mysql-configmap.yml -f mysql-deployment.yml -f mysql-svc.yml
        kubectl apply -f two-tier-app-deployment.yml -f two-tier-app-svc.yml
        kubectl get all
        kubectl get pods

    # - name: Deploy to EKS
    #   run: |
    #     kubectl apply -f path/to/your/k8s/deployment.yaml
